version: "3.3"

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    env_file: .env
    environment:
      PUID: $HOMEPAGE_PUID
      PGID: $HOMEPAGE_PGID
    ports:
      - 3000:3000
    volumes:
      - ~/projects/Exodus/config:/app/config # Make sure your local config directory exists
      - /media/omega:/media
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    env_file: .env
    environment:
      PUID: $PUID
      PGID: $PGID
    volumes:
      - ~/projects/Exodus/config:/config
      - /media/omega/anime:/data/anime
      - /media/omega/movies:/data/movies
      - /media/omega/tvshows:/data/tvshows
    ports:
      - 8096:8096
    restart: unless-stopped

  speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - '8080:80'
            - '8443:443'
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=speedy
            - DB_PASSWORD=password
        volumes:
            - speedtest-app:/config
            - './web:/etc/ssl/web'
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        restart: unless-stopped
        depends_on:
            - db

  db:
      image: mariadb:10
      restart: always
      environment:
          - MARIADB_DATABASE=speedtest_tracker
          - MARIADB_USER=speedy
          - MARIADB_PASSWORD=password
          - MARIADB_RANDOM_ROOT_PASSWORD=true
      volumes:
          - speedtest-db:/var/lib/mysql

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9443:9443
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  
volumes:
  speedtest-app:
  speedtest-db:
  portainer-data: