version: "3.3"

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    env_file: .env
    environment:
      PUID: $PUID
      PGID: $PGID
    ports:
      - 3000:3000
    volumes:
      - ~/projects/Exodus/config:/app/config # Make sure your local config directory exists
      - /media/omega:/media
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    env_file: .env
    environment:
      PUID: $PUID
      PGID: $PGID
    volumes:
      - ~/projects/Exodus/config:/config
      - /media/omega/anime:/data/anime
      - /media/omega/movies:/data/movies
      - /media/omega/tvshows:/data/tvshows
    ports:
      - 8096:8096
    restart: unless-stopped
