---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Media:
    - Jellyfin:
        icon: jellyfin.png
        href: http://192.168.1.120:8096
        description: The Free Software Media System
        widget:
            type: jellyfin
            url: http://192.168.1.120:8096
            key: "{{HOMEPAGE_VAR_JELLYFIN_API_KEY}}"
            enableBlocks: true # optional, defaults to false
            enableNowPlaying: true # optional, defaults to true
        server: my-docker
        container: jellyfin
        showStats: true
        statusStyle: 'dot'

- Network:
    - Speedtest:
        icon: speedtest-tracker.png
        href: http://192.168.1.120:8080
        description: A Self-Hosted Performance Tracking Application
        widget:
            type: speedtest
            url: http://192.168.1.120:8080
        server: my-docker
        container: speedtest-tracker
        showStats: true
        statusStyle: 'dot'
    - Portainer:
        icon: portainer.png
        href: https://192.168.1.120:9443
        description: Container Management Software for Kubernetes and Docker
        widget:
            type: portainer
            url: https://192.168.1.120:9443
            env: 2
            key: ptr_LC91Px1D2Z/897RuXnyvK7d+rMKPY+5A+86xtBa0c2U=
        server: my-docker
        container: portainer
        showStats: true
        statusStyle: 'dot'

# - My First Group:
#     - My First Service:
#         href: http://localhost/
#         description: Homepage is awesome

# - My Second Group:
#     - My Second Service:
#         href: http://localhost/
#         description: Homepage is the best

# - My Third Group:
#     - My Third Service:
#         href: http://localhost/
#         description: Homepage is 😎
